import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import AxiosProvider from '@/providers/AxiosProvider';
import { StoreProvider } from "@/stores/provider"
import { AuthGuard } from "@/components/AuthGuard"
import { Suspense } from "react"
import { Providers } from "../lib/QueryProvider";


/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
}); */

/* const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <Suspense fallback={<div>Carregando...</div>}>
        <Providers>
         <AxiosProvider> 
         <StoreProvider>
         <AuthGuard>
        {children}
        <Toaster />
        </AuthGuard>
        </StoreProvider>
        </AxiosProvider>
        
        </Providers>
        </Suspense>
      </body>
    </html>
  );
}
