version: '3'

networks:
  laravel:


services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
      - "8080:8080"
      
    volumes:
      - ./src:/var/www/html:cached
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nextjs
      - php 
      - mysql
      - mailhog
    networks:
      - laravel

  nextjs:
    build:
      context: .
      dockerfile: ./dockerfiles/nextjs.dockerfile
    volumes:
      - ./front:/var/www/html:cached
    ports:
      - "3000:3000"
    networks:
      - laravel
  
  queue-worker:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: always
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=mesax
      - DB_USERNAME=austin
      - DB_PASSWORD=923.Eddy
    depends_on:
      - mysql
    networks:
      - laravel
    command: "php artisan queue:work"

  reverb:
    build:
        context: ./dockerfiles
        dockerfile: php.dockerfile
        args:
          - UID=${UID:-1000}
          - GID=${GID:-1000}
    restart: always
    user: root
    volumes:
        - ./src:/var/www/html
        - ./dockerfiles/reverb-entrypoint.sh:/reverb-entrypoint.sh
    environment:
        - DB_HOST=mysql
        - DB_DATABASE=mesax
        - DB_USERNAME=austin
        - DB_PASSWORD=923.Eddy
        - REVERB_APP_ID=573699
        - REVERB_APP_KEY=qqmsdqbnqvuhmij41258
        - REVERB_APP_SECRET=fgvldq8bdjsbqqjssdf4564n6
        - REVERB_SERVER_HOST=0.0.0.0
        - REVERB_SERVER_PORT=8081
    
    ports:
        - "8081:8081"
    networks:
        - laravel
    entrypoint: ["/reverb-entrypoint.sh"]
    command: "sh -c 'chmod +x /reverb-entrypoint.sh && /reverb-entrypoint.sh'"
  
  
  mysql:
    image: mysql:9.2.0
    
    restart: always
    tty: true
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mesax         # Nome do banco de dados
      MYSQL_USER: austin            # Nome do usuário adicional
      MYSQL_PASSWORD: 923.Eddy      # Senha do usuário adicional
      MYSQL_ROOT_PASSWORD: 923.Eddy
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html:cached
      - ./dockerfiles/entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    depends_on:
      - mysql
      - redis
      - queue-worker
      - reverb
    networks:
      - laravel

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  composer:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1001}
        - GID=${GID:-1001}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel

  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - laravel

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:cached
    depends_on:
      - mysql
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel
  
  pest:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:cached
    depends_on:
      - mysql
      - redis
    entrypoint: [ 'vendor/bin/pest' ]
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - laravel
  
  