version: '3'

networks:
  laravel:
    name: laravel

services:
  # Traefik reverse proxy
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--api.insecure=true"  # Dashboard enabled but no auth (only for dev)
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/letsencrypt:/letsencrypt
    networks:
      - laravel
  
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./dockerfiles/nextjs.dockerfile
    volumes:
      - ./front:/var/www/html:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`next.localhost`)"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
    networks:
      - laravel
    depends_on:
      - traefik

  app:
    container_name: app
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:cached
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=mesax
      - DB_USERNAME=austin
      - DB_PASSWORD=923.Eddy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`laravel.localhost`)"
      - "traefik.http.services.laravel.loadbalancer.server.port=8000"
    depends_on:
      - traefik
      - mysql
      - redis
      - nextjs
      - reverb
      - queue-worker
      - mailhog
    networks:
      - laravel

  queue-worker:
    container_name: queue-worker
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: always
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=mesax
      - DB_USERNAME=austin
      - DB_PASSWORD=923.Eddy
    depends_on:
      - mysql
    networks:
      - laravel
    command: "/usr/local/bin/php artisan queue:work"

  reverb:
    container_name: reverb
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: always
    user: root
    volumes:
      - ./src:/var/www/html
      - ./dockerfiles/reverb-entrypoint.sh:/reverb-entrypoint.sh
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=mesax
      - DB_USERNAME=austin
      - DB_PASSWORD=923.Eddy
      - REVERB_APP_ID=573699
      - REVERB_APP_KEY=qqmsdqbnqvuhmij41258
      - REVERB_APP_SECRET=fgvldq8bdjsbqqjssdf4564n6
      - REVERB_SERVER_HOST=0.0.0.0
      - REVERB_SERVER_PORT=8081
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reverb.rule=Host(`reverb.localhost`)"
      - "traefik.http.services.reverb.loadbalancer.server.port=8081"
    networks:
      - laravel
   # command: "/usr/local/bin/php artisan reverb:start"
  
  mysql:
    container_name: mysql
    image: mysql:9.2.0
    restart: always
    tty: true
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mesax
      MYSQL_USER: austin
      MYSQL_PASSWORD: 923.Eddy
      MYSQL_ROOT_PASSWORD: 923.Eddy
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  composer:
    container_name: composer
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1001}
        - GID=${GID:-1001}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel

  npm:
    container_name: npm
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    ports:
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - laravel

  artisan:
    container_name: artisan
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:cached
    depends_on:
      - mysql
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel
  
  pest:
    container_name: pest
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:cached
    depends_on:
      - mysql
      - redis
    entrypoint: [ 'vendor/bin/pest' ]
    networks:
      - laravel

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.localhost`)"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
    networks:
      - laravel